### ISSUE TITLE
All Chinese and Japanese entries are excluded

### ISSUE THREAD

**Issue by abuccts** [newca12/dictionary-builder#10]
All Chinese and Japanese entries are excluded, how to preserve those entries?

**Comment by newca12** [comment]
If you have no entry (not excluded ) at all, I guess the language property is not correctly setted.
For example for the Chinese dictionary you could try : 
language=\u6F22\u8A9E
languageShort=zh

No warranty though

**Comment by abuccts** [comment]
I mean Chinese entries in en-wiktionary, with English content. All those entries are in `excludedFile` instead of wordsFile when I parsed English Wiktionary dumps..

**Comment by newca12** [comment]
I have push a new version to fix this.
You can now disable the language filter in dico.properties :
languageFilter=false
