### ISSUE TITLE
Error when reading in export-0.10, expected export-0.9

### ISSUE THREAD

**Issue by netinept** [newca12/dictionary-builder#7]
After cloning the repository and building the project, the following error is given when trying to run against  the latest wiktionary dump.

    Your dictionary is being built. Please wait.
    unexpected element (uri:"http://www.mediawiki.org/xml/export-0.10/", local:"mediawiki"). Expected elements are <{http://www.mediawiki.org/xml/export-0.9/}mediawiki>
    Sorry but your wikimedia dump is probably too old.
    If your wikimedia dump is up to date please fill out a problem report form and submit it : https://github.com/newca12/dictionary-builder/issues

**Comment by newca12** [comment]
Fixed (but not tested). Thanks for your bug report.

**Comment by newca12** [comment]
The fix for your issue rise another one. Both are now fixed (and verified) in the master branch.
Nota : instructions have changed, you now need to do mvn package to make the jar.
