### ISSUE TITLE
no entry for the property : wordsFile

### ISSUE THREAD

**Issue by Forwardboy009** [newca12/dictionary-builder#8]
After run "mvn package", it returned BUILD SUCCESS. But when run "java -jar target/dictionary-builder.jar" it returns the message 
"no entry for the property : wordsFile
add it to your config file dico.properties and try again."
When I searched in folder, there's no word and excluded files. What should I do? Please!!

**Comment by newca12** [comment]
You probably screw up the file "dictionary-builder/src/main/resources/org/edla/dico/construct/dico.properties" when you have edited it.
Double check this file and re-run mvn package.

**Comment by Forwardboy009** [comment]
When I change only xml path, it showing "Please, create the root folder /tmp/dico
and/or check/fix your config file dico.properties and try again." So I created a folder in My Document and set a parameter in dico.properties as per attached dico.properties.txt, returns "no entry for the property : wordsFile
add it to your config file dico.properties and try again." Pls help me.

[new 1.txt](https://github.com/newca12/dictionary-builder/files/372130/new.1.txt)

[dico.properties.txt](https://github.com/newca12/dictionary-builder/files/372087/dico.properties.txt)

**Comment by newca12** [comment]
Oh on Windows  "\" characters need to be escaped in properties file
Something like this :
root=C:\\Users\\Documents\\tmp\\dico
wordsFile=C:\\Users\\Documents\tmp\\dico\\words
excludedWordsFile=C:\\Users\\Documents\\tmp\\dico\\excluded
xmlFile=C:\\Users\\Documents\\tmp\\mywiktionary-latest-pages-articles.xml
language=Burmese
languageShort=my
expression=false

**Comment by Forwardboy009** [comment]
Thanks. Now it works. My typo in dico.properties.
